services:
  - type: web
    name: draftly
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SESSION_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true
