services:
  - type: web
    name: rotely
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SESSION_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATA_DIR
        value: /var/data
    autoDeploy: true
    disk:
      name: rotely-data
      mountPath: /var/data
      sizeGB: 1
